"""archivage des offres et titre de conversation

Deux colonnes facultatives, sans valeur par défaut : une offre existante
reste active (`archived_at` nul) et une conversation existante garde son
titre implicite (la première question posée).

Revision ID: 17f7976c47fb
Revises: 67e3bb86641c
Create Date: 2026-09-22 19:32:31.915393

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17f7976c47fb"
down_revision: str | Sequence[str] | None = "67e3bb86641c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("title", sa.String(length=200), nullable=True))
    op.add_column("jobs", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "archived_at")
    op.drop_column("conversations", "title")
    # ### end Alembic commands ###
