"""pipeline de preselection : issue et unicite des notations

Revision ID: 2ae74c5df3a8
Revises: 2675fe8d1bfd
Create Date: 2026-09-21 17:40:38.144151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ae74c5df3a8"
down_revision: str | Sequence[str] | None = "2675fe8d1bfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_scores",
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'scored'"), nullable=False
        ),
    )
    op.add_column("candidate_scores", sa.Column("error", sa.Text(), nullable=True))
    op.alter_column(
        "candidate_scores",
        "score_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("candidate_scores", "overall", existing_type=sa.INTEGER(), nullable=True)
    op.create_unique_constraint(
        op.f("uq_candidate_scores_run_id"), "candidate_scores", ["run_id", "candidate_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_candidate_scores_run_id"), "candidate_scores", type_="unique")
    op.alter_column("candidate_scores", "overall", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "candidate_scores",
        "score_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("candidate_scores", "error")
    op.drop_column("candidate_scores", "status")
    # ### end Alembic commands ###
