"""table coaching_sessions + RLS

Revision ID: 8108e1507ce2
Revises: cf264ddde083
Create Date: 2026-09-21 08:44:52.642390

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8108e1507ce2'
down_revision: str | Sequence[str] | None = 'cf264ddde083'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('overall_0_100', sa.Integer(), nullable=False),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('pending_write_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sf_task_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_coaching_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coaching_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaching_sessions'))
    )
    op.create_index(op.f('ix_coaching_sessions_organization_id'), 'coaching_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_trace_id'), 'coaching_sessions', ['trace_id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_user_id'), 'coaching_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security (ADR-002) : même politique que le socle ---------
    op.execute("ALTER TABLE coaching_sessions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE coaching_sessions FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation_coaching_sessions ON coaching_sessions "
        "USING (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )
    # Le runtime crée les sessions et met à jour la seule tâche journalisée.
    op.execute("GRANT SELECT, INSERT, UPDATE ON coaching_sessions TO miara_app")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaching_sessions_user_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_trace_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_organization_id'), table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    # ### end Alembic commands ###
