"""table llm_calls + RLS

Revision ID: bd44cb2ae1a3
Revises: f5f62cf40791
Create Date: 2026-09-19 06:40:13.522328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd44cb2ae1a3"
down_revision: str | Sequence[str] | None = "f5f62cf40791"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("agent", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("model_used", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("tool_calls_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_llm_calls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
    )
    op.create_index(
        op.f("ix_llm_calls_organization_id"), "llm_calls", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_llm_calls_trace_id"), "llm_calls", ["trace_id"], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security (ADR-002) : même politique que le socle ---------
    op.execute("ALTER TABLE llm_calls ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE llm_calls FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation_llm_calls ON llm_calls "
        "USING (organization_id = "
        "NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )
    # Journal en ajout seul pour le runtime : ni UPDATE ni DELETE.
    op.execute("GRANT SELECT, INSERT ON llm_calls TO miara_app")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_calls_trace_id"), table_name="llm_calls")
    op.drop_index(op.f("ix_llm_calls_organization_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    # ### end Alembic commands ###
