"""agent_traces.conversation_id

Revision ID: cf264ddde083
Revises: fa45aa4bda8b
Create Date: 2026-09-20 17:20:07.391118

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf264ddde083'
down_revision: str | Sequence[str] | None = 'fa45aa4bda8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_traces', sa.Column('conversation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_agent_traces_conversation_id'), 'agent_traces', ['conversation_id'], unique=False)
    op.create_foreign_key(op.f('fk_agent_traces_conversation_id_conversations'), 'agent_traces', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_agent_traces_conversation_id_conversations'), 'agent_traces', type_='foreignkey')
    op.drop_index(op.f('ix_agent_traces_conversation_id'), table_name='agent_traces')
    op.drop_column('agent_traces', 'conversation_id')
    # ### end Alembic commands ###
