"""table crm_writes + RLS

Revision ID: fa45aa4bda8b
Revises: 412720e7a320
Create Date: 2026-09-20 16:57:12.465300

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa45aa4bda8b'
down_revision: str | Sequence[str] | None = '412720e7a320'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_writes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('args_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sf_record_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_crm_writes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_writes'))
    )
    op.create_index(op.f('ix_crm_writes_confirmed_by'), 'crm_writes', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_crm_writes_organization_id'), 'crm_writes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_writes_trace_id'), 'crm_writes', ['trace_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security (ADR-002) : même politique que le socle ---------
    op.execute("ALTER TABLE crm_writes ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE crm_writes FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation_crm_writes ON crm_writes "
        "USING (organization_id = NULLIF(current_setting('app.current_org', true), '')::uuid)"
    )
    # Piste d'audit : le runtime ajoute et lit, jamais de modification/suppression.
    op.execute("GRANT SELECT, INSERT ON crm_writes TO miara_app")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_writes_trace_id'), table_name='crm_writes')
    op.drop_index(op.f('ix_crm_writes_organization_id'), table_name='crm_writes')
    op.drop_index(op.f('ix_crm_writes_confirmed_by'), table_name='crm_writes')
    op.drop_table('crm_writes')
    # ### end Alembic commands ###
